nelmio_cors:
  paths:
    '^/api/':
      origin_regex: true
      allow_origin: [ '^http://127\.0\.0\.1:[0-9]+','^http://localhost:[0-9]+' ] # You probably want to change this regex to match your real domain
      allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
      allow_headers: [ 'Content-Type', 'Authorization' ]
      expose_headers: [ 'Link' ]
      max_age: 3600
    '^/auth':
      origin_regex: true
      allow_origin: [ '^http://127\.0\.0\.1:[0-9]+','^http://localhost:[0-9]+' ] # You probably want to change this regex to match your real domain
      allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
      allow_headers: [ 'Content-Type', 'Authorization' ]
      expose_headers: [ 'Link' ]
      max_age: 3600
